grafana:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 7d

    serviceMonitorSelectorNilUsesHelmValues: false

    scrapeInterval: 15s

    additionalScrapeConfigs:
      - job_name: otel-collector
        static_configs:
          - targets:
              - otel-collector-opentelemetry-collector.observability.svc.cluster.local:8889
